package cmd

import (
	"fmt"
	"io"
	"io/ioutil"
	"log"
	"octochan/core"
	"os"
	"os/exec"
	"path/filepath"
	plug "plugin"
	"strings"
	"time"

	"github.com/fsnotify/fsnotify"
	"github.com/hashicorp/go-plugin"
	"github.com/spf13/cobra"
	"github.com/spf13/viper"
	"gopkg.in/natefinch/lumberjack.v2"
)

var (
	cfgFile  string
	scenario string
	fastMode bool
)

type PipelineCommand interface {
	Execute(input io.Reader, output io.Writer) error
}

type Pipeline struct {
	commands []PipelineCommand
}

func (p *Pipeline) AddCommand(cmd PipelineCommand) {
	p.commands = append(p.commands, cmd)
}

func (p *Pipeline) Run() error {
	if len(p.commands) == 0 {
		return fmt.Errorf("нет команд для выполнения")
	}

	var prevOut io.ReadCloser
	defer func() {
		if prevOut != nil {
			prevOut.Close()
		}
	}()

	firstCmd := p.commands[0]
	lastIdx := len(p.commands) - 1

	if len(p.commands) == 1 {
		return firstCmd.Execute(os.Stdin, os.Stdout)
	}

	for i, cmd := range p.commands[:lastIdx] {
		pr, pw := io.Pipe()
		defer pw.Close()

		go func(cmd PipelineCommand, i int, r io.Reader, w io.WriteCloser) {
			defer w.Close()
			if err := cmd.Execute(r, w); err != nil {
				fmt.Printf("Ошибка в команде %d: %v\n", i+1, err)
			}
		}(cmd, i, getInput(i, prevOut), pw)

		prevOut = pr
	}

	return p.commands[lastIdx].Execute(prevOut, os.Stdout)
}

func getInput(index int, prevOut io.Reader) io.Reader {
	if index == 0 {
		return os.Stdin
	}
	return prevOut
}

var diffCmd = &cobra.Command{
	Use:   "diff <file1> <file2>",
	Short: "Сравнить два конфигурационных файла",
	Args:  cobra.ExactArgs(2),
	Run: func(cmd *cobra.Command, args []string) {
		scriptDir, err := core.GetScriptDir()
		if err != nil {
			fmt.Printf("Ошибка получения директории скрипта: %v\n", err)
			return
		}

		reportsDir := filepath.Join(scriptDir, "reports")
		snapshotsDir := filepath.Join(scriptDir, "snapshots")
		for _, dir := range []string{reportsDir, snapshotsDir} {
			if err := os.MkdirAll(dir, 0755); err != nil {
				fmt.Printf("Ошибка создания директории %s: %v\n", dir, err)
				return
			}
		}

		file1 := resolveInputPath(args[0], scriptDir, reportsDir)
		file2 := resolveInputPath(args[1], scriptDir, reportsDir)

		if !core.FileExists(file1) || !core.FileExists(file2) {
			fmt.Printf("Один из файлов не найден\n")
			return
		}

		content1, _ := core.ReadFile(file1)
		content2, _ := core.ReadFile(file2)
		cfg1, _ := core.ParseConfig(content1)
		cfg2, _ := core.ParseConfig(content2)

		diff := core.CompareConfigs(cfg1, cfg2, file1, file2)

		if len(diff) == 0 {
			fmt.Println("Файлы идентичны!")
			return
		}

		if fastMode {
			fmt.Println("Найдены различия (fast mode):")
			for param, vals := range diff {
				fmt.Printf("%s: %s -> %s\n", param, vals[file1], vals[file2])
			}
			return
		}

		fmt.Println("Найдены различия:")
		for param, vals := range diff {
			fmt.Printf("%s:\n  %s -> %s\n", param, vals[file1], vals[file2])
		}

		reportNum, _ := core.GetNextReportNumber(reportsDir)
		outputFile := filepath.Join(reportsDir, fmt.Sprintf("diff_report_%d.txt", reportNum))
		core.SaveDiffToFile(diff, outputFile, file1, file2)
		fmt.Printf("\nОтчет сохранен в: %s\n", outputFile)

		snapshot, err := core.CreateSnapshot(nil, cfg1, cfg2, "system", "autogenerated")
		if err != nil {
			fmt.Printf("Ошибка создания снапшота: %v\n", err)
			return
		}
		if err := core.SaveSnapshot(snapshot, snapshotsDir); err != nil {
			fmt.Printf("Ошибка сохранения снапшота: %v\n", err)
			return
		}
		fmt.Printf("Снапшот создан: %s\n", snapshot.ID)
	},
}

var saveScenarioCmd = &cobra.Command{
	Use:   "srs <scenario.yaml>",
	Short: "Сохранить сценарий в бинарник",
	Args:  cobra.ExactArgs(1),
	Run: func(cmd *cobra.Command, args []string) {
		scenarioPath := args[0]
		data, err := os.ReadFile(scenarioPath)
		if err != nil {
			fmt.Printf("❌ Ошибка чтения файла: %v\n", err)
			return
		}

		fm, err := core.NewFileManager()
		if err != nil {
			fmt.Printf("❌ Ошибка инициализации файлового менеджера: %v\n", err)
			return
		}

		scenarioName := strings.TrimSuffix(filepath.Base(scenarioPath), ".yaml")
		if err := fm.SaveScenario(scenarioName, data); err != nil {
			fmt.Printf("❌ Ошибка сохранения: %v\n", err)
			return
		}

		// Исправлено: вызываем метод BaseDir()
		savePath := filepath.Join(fm.BaseDir(), scenarioName+".bin")
		fmt.Printf("✅ Сценарий сохранён: %s\n", savePath)
	},
}

var applyCmd = &cobra.Command{
	Use:   "apply [-rlm] <file> [custom_params...]",
	Short: "Применить сценарий или конфигурацию",
	Long: `Применяет сценарий или конфигурацию в зависимости от флагов.
С флагом -rlm работает с RLM сценариями. Для RLM сценариев можно передавать
дополнительные параметры в формате key=value.`,
	Args: cobra.MinimumNArgs(1),
	Run: func(cmd *cobra.Command, args []string) {
		useRLM, _ := cmd.Flags().GetBool("rlm")

		if useRLM {
			log.Println("=== Starting new apply operation ===")
			defer log.Println("=== Apply operation completed ===")

			customParams := make(map[string]string)
			if len(args) > 1 {
				for _, param := range args[1:] {
					parts := strings.SplitN(param, "=", 2)
					if len(parts) == 2 {
						customParams[parts[0]] = parts[1]
						log.Printf("Added custom param: %s=%s", parts[0], parts[1])
					} else {
						log.Printf("⚠️ Invalid parameter format: %s", param)
					}
				}
			}

			token := viper.GetString("defaults.api_token")
			if token == "" {
				fmt.Println("❌ Токен не установлен. Используйте команду 'auth' для установки токена")
				return
			}
			taskIDs, err := core.ExecuteScenarioFromFile(args[0], customParams)
			if err != nil {
				fmt.Printf("❌ Ошибка выполнения сценария: %v\n", err)
				return
			}
			fmt.Println("✅ Созданные задачи:")
			for _, taskID := range taskIDs {
				fmt.Printf("- %s\n", taskID)
			}

			if viper.GetBool("defaults.auto_check_status") {
				fmt.Println("\n🔄 Проверка статусов задач...")
				for _, taskID := range taskIDs {
					status, err := core.GetTaskStatus(taskID)
					if err != nil {
						fmt.Printf("⚠️ Не удалось проверить статус задачи %s: %v\n", taskID, err)
					} else {
						fmt.Printf("- %s: %s\n", taskID, status["status"])
					}
				}
			}
		} else {
			fmt.Println("Применение обычного конфига...")
		}
	},
}

func resolveInputPath(inputPath, scriptDir, reportsDir string) string {

	if filepath.IsAbs(inputPath) {
		return inputPath
	}

	if core.FileExists(inputPath) {
		return inputPath
	}

	scriptPath := filepath.Join(scriptDir, inputPath)
	if core.FileExists(scriptPath) {
		return scriptPath
	}

	reportsPath := filepath.Join(reportsDir, inputPath)
	if core.FileExists(reportsPath) {
		return reportsPath
	}

	return inputPath
}

var listModulesCmd = &cobra.Command{
	Use:   "modules",
	Short: "Показать установленные модули",
	Run: func(cmd *cobra.Command, args []string) {
		fm, _ := core.NewFileManager()
		files, _ := os.ReadDir(fm.ModulesDir())
		for _, f := range files {
			fmt.Println(f.Name())
		}
	},
}

var logsCmd = &cobra.Command{
	Use:   "logs [--tail N]",
	Short: "Показать логи",
	Run: func(cmd *cobra.Command, args []string) {
		tail, _ := cmd.Flags().GetInt("tail")
		showLogs(tail)
	},
}

var findCmd = &cobra.Command{
	Use:   "find <file> <parameter>",
	Short: "Найти параметр в конфиге",
	Run: func(cmd *cobra.Command, args []string) {
		content, _ := os.ReadFile(args[0])
		cfg, _ := core.ParseConfig(string(content))

		for section, params := range cfg {
			if val, ok := params[args[1]]; ok {
				fmt.Printf("[%s] %s = %v\n", section, args[1], val)
			}
		}
	},
}

var installCmd = &cobra.Command{
	Use:   "!install <module_file>",
	Short: "Установить новый модуль команд",
	Long: `Устанавливает модуль команд из файла. Поддерживает только .hcplugin плагины,
которые используют Hashicorp plugin system для динамической загрузки.`,
	Args: cobra.ExactArgs(1),
	Run: func(cmd *cobra.Command, args []string) {
		filePath := args[0]

		// 1. Проверка файла
		if !strings.HasSuffix(filePath, ".hcplugin") {
			cmd.PrintErrln("❌ Поддерживаются только .hcplugin модули")
			return
		}

		// 2. Чтение файла
		data, err := os.ReadFile(filePath)
		if err != nil {
			cmd.PrintErrf("❌ Ошибка чтения файла модуля: %v\n", err)
			return
		}

		// 3. Инициализация файлового менеджера
		fm, err := core.NewFileManager()
		if err != nil {
			cmd.PrintErrf("❌ Ошибка инициализации файлового менеджера: %v\n", err)
			return
		}

		moduleName := filepath.Base(filePath)

		// 4. Установка модуля
		if err := fm.InstallHashicorpModule(moduleName, data); err != nil {
			cmd.PrintErrf("❌ Ошибка установки модуля: %v\n", err)
			return
		}

		// 5. Загрузка модуля
		modulePath := filepath.Join(fm.ModulesDir(), moduleName)
		if err := core.GetModuleManager().LoadHashicorpPlugin(modulePath); err != nil {
			cmd.PrintErrf("⚠️ Ошибка загрузки плагина: %v\n", err)

			// Попытка удалить нерабочий модуль
			if removeErr := os.Remove(modulePath); removeErr != nil {
				cmd.PrintErrf("⚠️ Не удалось удалить нерабочий модуль: %v\n", removeErr)
			}
			return
		}

		// 6. Отчет об успешной установке
		cmd.Printf("✅ Модуль [%s] успешно установлен и загружен\n", moduleName)
	},
}
var helpCmd = &cobra.Command{
	Use:   "help",
	Short: "Отобразить список всех доступных команд",
	Long: `Отображает подробную информацию о всех доступных командах
и их использовании`,
	Run: func(cmd *cobra.Command, args []string) {
		fmt.Println("Доступные команды:")
		fmt.Println("------------------")

		for _, subCmd := range rootCmd.Commands() {
			fmt.Printf("%-10s - %s\n", subCmd.Use, subCmd.Short)

			if subCmd.Example != "" {
				fmt.Printf("  Пример: %s\n", subCmd.Example)
			}
		}
	},
}

var patchCmd = &cobra.Command{
	Use:   "patch <base_file> <changes_file>",
	Short: "Применить изменения к основному конфигу",
	Run: func(cmd *cobra.Command, args []string) {
		content1, err := core.ReadFile(args[0])
		if err != nil {
			fmt.Printf("Ошибка чтения файла: %v\n", err)
			return
		}

		content2, err := core.ReadFile(args[1])
		if err != nil {
			fmt.Printf("Ошибка чтения файла: %v\n", err)
			return
		}

		base, err := core.ParseConfig(content1)
		if err != nil {
			fmt.Printf("Ошибка парсинга: %v\n", err)
			return
		}

		changes, err := core.ParseConfig(content2)
		if err != nil {
			fmt.Printf("Ошибка парсинга: %v\n", err)
			return
		}

		for section, params := range changes {
			if _, exists := base[section]; !exists {
				base[section] = make(map[string]string)
			}
			for k, v := range params {
				base[section][k] = v
			}
		}

		if err := core.SaveConfig(base, "patched.conf"); err != nil {
			fmt.Printf("Ошибка сохранения: %v\n", err)
			return
		}
		fmt.Println("Изменения успешно применены и сохранены в patched.conf")
	},
}

var authCmd = &cobra.Command{
	Use:   "auth <token>",
	Short: "Установить токен для доступа к RLM API",
	Args:  cobra.ExactArgs(1),
	Run: func(cmd *cobra.Command, args []string) {
		initConfig()

		viper.Set("defaults.api_token", args[0])
		if err := viper.WriteConfig(); err != nil {
			fmt.Printf("❌ Ошибка сохранения токена: %v\n", err)
			return
		}
		fmt.Println("✅ Токен успешно сохранен")
	},
}
var statusCmd = &cobra.Command{
	Use:   "status <task_id>",
	Short: "Проверить статус выполнения задачи",
	Args:  cobra.ExactArgs(1),
	Run: func(cmd *cobra.Command, args []string) {
		taskID := args[0]
		if err := core.PrintTaskStatus(taskID); err != nil {
			fmt.Printf("❌ Ошибка: %v\n", err)
			return
		}
	},
}

var statsCmd = &cobra.Command{
	Use:   "stats <file>",
	Short: "Показать статистику конфига",
	Run: func(cmd *cobra.Command, args []string) {
		content, err := core.ReadFile(args[0])
		if err != nil {
			fmt.Printf("Ошибка чтения файла: %v\n", err)
			return
		}

		cfg, err := core.ParseConfig(content)
		if err != nil {
			fmt.Printf("Ошибка парсинга: %v\n", err)
			return
		}

		fmt.Printf("Секций: %d\n", len(cfg))
		totalParams := 0
		for _, params := range cfg {
			totalParams += len(params)
		}
		fmt.Printf("Параметров: %d\n", totalParams)
	},
}
var validateCmd = &cobra.Command{
	Use:   "validate <file>",
	Short: "Проверить конфиг на ошибки",
	Run: func(cmd *cobra.Command, args []string) {
		content, _ := os.ReadFile(args[0])
		_, err := core.ParseConfig(string(content))
		if err != nil {
			fmt.Printf(" Ошибка: %v\n", err)
			return
		}
		fmt.Println("Конфиг валиден")
	},
}

func initConfig() {
	home, err := os.UserHomeDir()
	if err != nil {
		fmt.Printf("❌ Ошибка определения домашней директории: %v\n", err)
		return
	}

	dirs := []string{
		filepath.Join(home, ".octochan"),
		filepath.Join(home, ".octochan", "scenarios"),
		filepath.Join(home, ".octochan", "reports"),
		filepath.Join(home, ".octochan", "snapshots"),
		filepath.Join(home, ".octochan", "logs"),
		filepath.Join(home, "octochan"),
	}

	for _, dir := range dirs {
		if err := os.MkdirAll(dir, 0755); err != nil {
			fmt.Printf("❌ Ошибка создания директории %s: %v\n", dir, err)
			return
		}
	}

	cfgPath := filepath.Join(home, "octochan", "config.yaml")
	viper.SetConfigFile(cfgPath)

	if _, err := os.Stat(cfgPath); os.IsNotExist(err) {
		viper.Set("defaults.api_url", "https://rlm.sigma.sbrf.ru/api/tasks.json")
		viper.Set("defaults.scenario_path", filepath.Join(home, ".octochan", "scenarios"))
		viper.Set("defaults.auto_check_status", false)
		viper.Set("defaults.max_parallel_tasks", 5)
		viper.Set("defaults.log_path", filepath.Join(home, ".octochan", "logs"))
		viper.Set("defaults.log_max_size", 10)
		viper.Set("defaults.log_max_backups", 5)
		if err := viper.WriteConfig(); err != nil {
			fmt.Printf("❌ Ошибка создания конфига: %v\n", err)
		}
	}

	if err := viper.ReadInConfig(); err == nil {
		fmt.Println("⚙️ Используется конфиг:", viper.ConfigFileUsed())
	}
}
func showLogs(tail int) {
	logPath := viper.GetString("defaults.log_path")
	if logPath == "" {
		home, _ := os.UserHomeDir()
		logPath = filepath.Join(home, ".octochan", "logs")
	}

	logFile := filepath.Join(logPath, "octochan.log")

	if _, err := os.Stat(logFile); os.IsNotExist(err) {
		fmt.Println("ℹ️ Лог-файл ещё не создан, пока нет записей")
		return
	}

	content, err := ioutil.ReadFile(logFile)
	if err != nil {
		fmt.Printf("❌ Ошибка чтения логов: %v\n", err)
		return
	}

	lines := strings.Split(string(content), "\n")

	if tail <= 0 || tail >= len(lines) {
		fmt.Println(string(content))
		return
	}

	start := len(lines) - tail
	if start < 0 {
		start = 0
	}

	fmt.Println("Последние", tail, "строк логов:")
	for _, line := range lines[start:] {
		fmt.Println(line)
	}
}

func initLogger() {
	logPath := viper.GetString("defaults.log_path")
	if logPath == "" {
		home, _ := os.UserHomeDir()
		logPath = filepath.Join(home, ".octochan", "logs")
	}

	if err := os.MkdirAll(logPath, 0755); err != nil {
		fmt.Printf("❌ Ошибка создания директории логов: %v\n", err)
		os.Exit(1)
	}

	logFile := filepath.Join(logPath, "rlm-cli.log")
	writer := &lumberjack.Logger{
		Filename:   logFile,
		MaxSize:    viper.GetInt("defaults.log_max_size"),
		MaxBackups: viper.GetInt("defaults.log_max_backups"),
		Compress:   true,
	}

	log.SetOutput(io.MultiWriter(os.Stdout, writer))
	log.SetFlags(log.LstdFlags | log.Lshortfile)
}

func watchModules() {
	fm, err := core.NewFileManager()
	if err != nil {
		log.Printf("❌ Не удалось инициализировать FileManager: %v", err)
		return
	}

	watcher, err := fsnotify.NewWatcher()
	if err != nil {
		log.Printf("❌ Не удалось создать watcher: %v", err)
		return
	}
	defer watcher.Close()

	err = watcher.Add(fm.ModulesDir())
	if err != nil {
		log.Printf("❌ Не удалось добавить директорию для наблюдения: %v", err)
		return
	}

	log.Println("🔍 Наблюдение за изменениями модулей запущено")

	for {
		select {
		case event, ok := <-watcher.Events:
			if !ok {
				return
			}

			// Обрабатываем только события записи для .hcplugin файлов
			if event.Op&fsnotify.Write == fsnotify.Write &&
				strings.HasSuffix(event.Name, ".hcplugin") {
				log.Printf("Обнаружено изменение модуля: %s", event.Name)

				// Перезагружаем модуль
				if err := core.GetModuleManager().LoadHashicorpPlugin(event.Name); err != nil {
					log.Printf("⚠️ Не удалось перезагрузить модуль %s: %v", event.Name, err)
				} else {
					log.Printf("✅ Модуль %s успешно перезагружен", event.Name)
				}
			}

		case err, ok := <-watcher.Errors:
			if !ok {
				return
			}
			log.Printf("Ошибка watcher: %v", err)
		}
	}
}

func CheckModule(path string) error {
	plug, err := plug.Open(path)
	if err != nil {
		return err
	}

	symbols, err := plug.Lookup("")
	if err != nil {
		return err
	}

	fmt.Printf("Доступные символы в модуле %s:\n", path)
	for name := range symbols.(map[string]interface{}) {
		fmt.Println("-", name)
	}
	return nil
}

func inspectModule(path string) error {
	// Только для .hcplugin модулей
	if !strings.HasSuffix(path, ".hcplugin") {
		return fmt.Errorf("поддерживаются только .hcplugin модули")
	}

	// Временная загрузка модуля для проверки
	client := plugin.NewClient(&plugin.ClientConfig{
		HandshakeConfig: plugin.HandshakeConfig{
			ProtocolVersion:  1,
			MagicCookieKey:   "OCTOCHAN_PLUGIN",
			MagicCookieValue: "octochan-2025",
		},
		Plugins:      map[string]plugin.Plugin{"command": &core.CommandPlugin{}},
		Cmd:          exec.Command(path),
		StartTimeout: 10 * time.Second,
	})
	defer client.Kill()

	rpcClient, err := client.Client()
	if err != nil {
		return fmt.Errorf("не удалось подключиться к модулю: %w", err)
	}

	raw, err := rpcClient.Dispense("command")
	if err != nil {
		return fmt.Errorf("не удалось получить интерфейс команды: %w", err)
	}

	module, ok := raw.(core.CommandModule)
	if !ok {
		return fmt.Errorf("модуль не реализует CommandModule интерфейс")
	}

	fmt.Printf("Информация о модуле %s:\n", path)
	fmt.Printf("- Имя: %s\n", module.Name())
	fmt.Printf("- Версия: %s\n", module.Version())
	fmt.Println("- Команды:")
	for _, cmd := range module.GetCommands() {
		fmt.Printf("  * %s - %s\n", cmd.Use, cmd.Short)
	}

	return nil
}

func loadModules() {
	fm, err := core.NewFileManager()
	if err != nil {
		log.Printf("⚠️ Не удалось инициализировать FileManager: %v", err)
		return
	}

	if err := core.GetModuleManager().LoadModulesFromDir(fm.ModulesDir()); err != nil {
		log.Printf("⚠️ Ошибка при загрузке модулей: %v", err)
	}
}
func init() {
	cobra.OnInitialize(initConfig, initLogger, loadModules)
	diffCmd.Flags().BoolVarP(&fastMode, "fast", "f", false, "Только вывод в консоль без генерации файлов")
	rootCmd.AddCommand(diffCmd)
	cobra.OnInitialize(initConfig, initLogger, loadModules)
	rootCmd.AddCommand(validateCmd)
	rootCmd.AddCommand(findCmd)
	rootCmd.AddCommand(patchCmd)
	rootCmd.AddCommand(statsCmd)
	rootCmd.SetHelpCommand(helpCmd)
	rootCmd.AddCommand(helpCmd)
	cobra.OnInitialize(initConfig)
	rootCmd.PersistentFlags().StringVar(&cfgFile, "config", "", "Конфиг (default: ~/.rlm-cli/config.yaml)")
	rootCmd.AddCommand(saveScenarioCmd)
	rootCmd.AddCommand(authCmd)
	rootCmd.AddCommand(statusCmd)
	applyCmd.Flags().BoolP("rlm", "r", false, "Использовать RLM сценарий")
	rootCmd.AddCommand(applyCmd)
	logsCmd.Flags().Int("tail", 0, "Показать последние N строк логов (0 - все логи)")
	rootCmd.AddCommand(logsCmd)
	rootCmd.AddCommand(listModulesCmd)
	rootCmd.AddCommand(installCmd)
	moduleManager := core.GetModuleManager()
	for _, cmd := range moduleManager.GetCommands() {
		rootCmd.AddCommand(cmd)
	}
}
