package cmd

import (
	"bufio"
	"context"
	"fmt"
	"io"
	"log"
	"octochan/core"
	"os"
	"os/exec"
	"path/filepath"
	"strconv"
	"strings"
	"time"

	"github.com/fsnotify/fsnotify"
	"github.com/hashicorp/go-hclog"
	"github.com/hashicorp/go-plugin"
	"github.com/spf13/cobra"
	"github.com/spf13/viper"
	"gopkg.in/natefinch/lumberjack.v2"
)

var (
	cfgFile  string
	fastMode bool
	watcher  *fsnotify.Watcher
)

var diffCmd = &cobra.Command{
	Use:   "diff <file1> <file2>",
	Short: "Сравнить два конфигурационных файла",
	Args:  cobra.RangeArgs(1, 2), // Теперь 1-2 аргумента вместо строго 2
	Run: func(cmd *cobra.Command, args []string) {
		scriptDir, err := core.GetScriptDir()
		if err != nil {
			fmt.Printf("Ошибка получения директории скрипта: %v\n", err)
			return
		}
		reportsDir := filepath.Join(scriptDir, "reports")
		snapshotsDir := filepath.Join(scriptDir, "snapshots")

		for _, dir := range []string{reportsDir, snapshotsDir} {
			if err := os.MkdirAll(dir, 0755); err != nil {
				fmt.Printf("Ошибка создания директории %s: %v\n", dir, err)
				return
			}
		}

		var content1, content2 string
		var file1, file2 string
		if len(args) > 0 {
			if args[0] == "-" {
				stdinData, err := io.ReadAll(os.Stdin)
				if err != nil {
					fmt.Printf("❌ Ошибка чтения stdin: %v\n", err)
					return
				}
				content1 = string(stdinData)
				file1 = "stdin"
			} else {
				file1 = resolveInputPath(args[0], scriptDir, reportsDir)
				if !core.FileExists(file1) {
					fmt.Printf("❌ Файл не найден: %s\n", args[0])
					return
				}
				content, err := core.ReadFile(file1)
				if err != nil {
					fmt.Printf("❌ Ошибка чтения файла: %v\n", err)
					return
				}
				content1 = string(content)
			}
		}

		if len(args) > 1 {
			if args[1] == "-" {
				if file1 == "stdin" {
					fmt.Println("❌ Нельзя использовать stdin для обоих файлов")
					return
				}
				stdinData, err := io.ReadAll(os.Stdin)
				if err != nil {
					fmt.Printf("❌ Ошибка чтения stdin: %v\n", err)
					return
				}
				content2 = string(stdinData)
				file2 = "stdin"
			} else {
				file2 = resolveInputPath(args[1], scriptDir, reportsDir)
				if !core.FileExists(file2) {
					fmt.Printf("❌ Файл не найден: %s\n", args[1])
					return
				}
				content, err := core.ReadFile(file2)
				if err != nil {
					fmt.Printf("❌ Ошибка чтения файла: %v\n", err)
					return
				}
				content2 = string(content)
			}
		} else {
			content2 = ""
			file2 = "empty"
		}

		cfg1, err := core.ParseConfig(content1)
		if err != nil {
			fmt.Printf("❌ Ошибка парсинга первого конфига: %v\n", err)
			return
		}

		cfg2, err := core.ParseConfig(content2)
		if err != nil {
			fmt.Printf("❌ Ошибка парсинга второго конфига: %v\n", err)
			return
		}

		diff := core.CompareConfigs(cfg1, cfg2, file1, file2)

		if len(diff) == 0 {
			fmt.Println("Файлы идентичны!")
			return
		}

		if fastMode {
			fmt.Println("Найдены различия (fast mode):")
			for param, vals := range diff {
				fmt.Printf("%s: %s -> %s\n", param, vals[file1], vals[file2])
			}
			return
		}

		fmt.Println("Найдены различия:")
		for param, vals := range diff {
			fmt.Printf("%s:\n  %s -> %s\n", param, vals[file1], vals[file2])
		}
		if !IsPipeMode() {
			reportNum, _ := core.GetNextReportNumber(reportsDir)
			outputFile := filepath.Join(reportsDir, fmt.Sprintf("diff_report_%d.txt", reportNum))
			core.SaveDiffToFile(diff, outputFile, file1, file2)
			fmt.Printf("\nОтчет сохранен в: %s\n", outputFile)

			snapshot, err := core.CreateSnapshot(nil, cfg1, cfg2, "system", "autogenerated")
			if err != nil {
				fmt.Printf("Ошибка создания снапшота: %v\n", err)
				return
			}
			if err := core.SaveSnapshot(snapshot, snapshotsDir); err != nil {
				fmt.Printf("Ошибка сохранения снапшота: %v\n", err)
				return
			}
			fmt.Printf("Снапшот создан: %s\n", snapshot.ID)
		}
	},
}

var inspectCmd = &cobra.Command{
	Use:   "inspect <module_path>",
	Short: "Проверить информацию о модуле",
	Args:  cobra.ExactArgs(1),
	Run: func(cmd *cobra.Command, args []string) {
		if err := inspectModule(args[0]); err != nil {
			fmt.Printf("❌ Ошибка: %v\n", err)
		}
	},
}
var saveScenarioCmd = &cobra.Command{
	Use:   "srs <scenario.yaml>",
	Short: "Сохранить сценарий в бинарник",
	Args:  cobra.ExactArgs(1),
	Run: func(cmd *cobra.Command, args []string) {
		scenarioPath := args[0]
		data, err := os.ReadFile(scenarioPath)
		if err != nil {
			fmt.Printf("❌ Ошибка чтения файла: %v\n", err)
			return
		}

		fm, err := core.NewFileManager()
		if err != nil {
			fmt.Printf("❌ Ошибка инициализации файлового менеджера: %v\n", err)
			return
		}

		scenarioName := strings.TrimSuffix(filepath.Base(scenarioPath), ".yaml")
		if err := fm.SaveScenario(scenarioName, data); err != nil {
			fmt.Printf("❌ Ошибка сохранения: %v\n", err)
			return
		}

		savePath := filepath.Join(fm.BaseDir(), scenarioName+".bin")
		fmt.Printf("✅ Сценарий сохранён: %s\n", savePath)
	},
}

var listModulesCmd = &cobra.Command{
	Use:   "modules",
	Short: "Показать установленные модули",
	Run: func(cmd *cobra.Command, args []string) {
		fm, _ := core.NewFileManager()
		files, _ := os.ReadDir(fm.ModulesDir())
		for _, f := range files {
			fmt.Println(f.Name())
		}
	},
}

var logsCmd = &cobra.Command{
	Use:   "logs [--tail N]",
	Short: "Показать логи",
	Run: func(cmd *cobra.Command, args []string) {
		tail, _ := cmd.Flags().GetInt("tail")
		showLogs(tail)
	},
}

var findCmd = &cobra.Command{
	Use:   "find <file> <parameter>",
	Short: "Найти параметр в конфиге",
	Run: func(cmd *cobra.Command, args []string) {
		content, _ := os.ReadFile(args[0])
		cfg, _ := core.ParseConfig(string(content))

		for section, params := range cfg {
			if val, ok := params[args[1]]; ok {
				fmt.Printf("[%s] %s = %v\n", section, args[1], val)
			}
		}
	},
}

var installCmd = &cobra.Command{
	Use:   "!install <module_file>",
	Short: "Установить новый модуль команд",
	Args:  cobra.ExactArgs(1),
	Run: func(cmd *cobra.Command, args []string) {
		filePath := args[0]

		if !strings.HasSuffix(filePath, ".hcplugin") {
			cmd.PrintErrln("❌ Поддерживаются только .hcplugin модули")
			return
		}

		data, err := os.ReadFile(filePath)
		if err != nil {
			cmd.PrintErrf("❌ Ошибка чтения файла модуля: %v\n", err)
			return
		}

		fm, err := core.NewFileManager()
		if err != nil {
			cmd.PrintErrf("❌ Ошибка инициализации файлового менеджера: %v\n", err)
			return
		}

		moduleName := filepath.Base(filePath)

		if err := fm.InstallHashicorpModule(moduleName, data); err != nil {
			cmd.PrintErrf("❌ Ошибка установки модуля: %v\n", err)
			return
		}

		modulePath := filepath.Join(fm.ModulesDir(), moduleName)
		if err := core.GetModuleManager().LoadHashicorpPlugin(modulePath); err != nil {
			cmd.PrintErrf("⚠️ Ошибка загрузки плагина: %v\n", err)

			if removeErr := os.Remove(modulePath); removeErr != nil {
				cmd.PrintErrf("⚠️ Не удалось удалить нерабочий модуль: %v\n", removeErr)
			}
			return
		}

		cmd.Printf("✅ Модуль [%s] успешно установлен и загружен\n", moduleName)
	},
}

var helpCmd = &cobra.Command{
	Use:   "help",
	Short: "Отобразить список всех доступных команд",
	Run: func(cmd *cobra.Command, args []string) {
		fmt.Println("Доступные команды:")
		fmt.Println("------------------")

		for _, subCmd := range rootCmd.Commands() {
			fmt.Printf("%-10s - %s\n", subCmd.Use, subCmd.Short)

			if subCmd.Example != "" {
				fmt.Printf("  Пример: %s\n", subCmd.Example)
			}
		}
	},
}

var patchCmd = &cobra.Command{
	Use:   "patch <base_file> <changes_file>",
	Short: "Применить изменения к основному конфигу",
	Run: func(cmd *cobra.Command, args []string) {
		content1, err := core.ReadFile(args[0])
		if err != nil {
			fmt.Printf("Ошибка чтения файла: %v\n", err)
			return
		}

		content2, err := core.ReadFile(args[1])
		if err != nil {
			fmt.Printf("Ошибка чтения файла: %v\n", err)
			return
		}

		base, err := core.ParseConfig(content1)
		if err != nil {
			fmt.Printf("Ошибка парсинга: %v\n", err)
			return
		}

		changes, err := core.ParseConfig(content2)
		if err != nil {
			fmt.Printf("Ошибка парсинга: %v\n", err)
			return
		}

		for section, params := range changes {
			if _, exists := base[section]; !exists {
				base[section] = make(map[string]string)
			}
			for k, v := range params {
				base[section][k] = v
			}
		}

		if err := core.SaveConfig(base, "patched.conf"); err != nil {
			fmt.Printf("Ошибка сохранения: %v\n", err)
			return
		}
		fmt.Println("Изменения успешно применены и сохранены в patched.conf")
	},
}

var authCmd = &cobra.Command{
	Use:   "auth [token]",
	Short: "Установить токен для доступа к RLM API",
	Args:  cobra.MaximumNArgs(2), // Изменили на 2
	Run: func(cmd *cobra.Command, args []string) {
		initConfig()

		var token string
		if len(args) == 0 {
			fmt.Print("Введите токен: ")
			scanner := bufio.NewScanner(os.Stdin)
			scanner.Scan()
			token = strings.TrimSpace(scanner.Text())
		} else if len(args) == 2 && strings.EqualFold(args[0], "token") {
			token = strings.TrimSpace(args[1])
		} else {
			token = strings.TrimSpace(args[0])
		}

		home, err := os.UserHomeDir()
		if err != nil {
			fmt.Printf("❌ Ошибка определения домашней директории: %v\n", err)
			return
		}

		envPath := filepath.Join(home, ".octochan", ".env")
		envContent := fmt.Sprintf("API_TOKEN=%s\n", token)

		if err := os.WriteFile(envPath, []byte(envContent), 0600); err != nil {
			fmt.Printf("❌ Ошибка сохранения токена: %v\n", err)
			return
		}

		if viper.GetBool("defaults.token_timer_enabled") {
			go startTokenTimer()
		}

		fmt.Println("✅ Токен успешно сохранен")
	},
}
var statusCmd = &cobra.Command{
	Use:   "status <task_id>",
	Short: "Проверить статус выполнения задачи",
	Args:  cobra.ExactArgs(1),
	Run: func(cmd *cobra.Command, args []string) {
		taskID := args[0]
		if err := core.PrintTaskStatus(taskID); err != nil {
			fmt.Printf("❌ Ошибка: %v\n", err)
			return
		}
	},
}

func loadEnv() {
	home, err := os.UserHomeDir()
	if err != nil {
		return
	}

	envPath := filepath.Join(home, ".octochan", ".env")
	if _, err := os.Stat(envPath); os.IsNotExist(err) {
		return
	}

	envFile, err := os.ReadFile(envPath)
	if err != nil {
		return
	}

	lines := strings.Split(string(envFile), "\n")
	for _, line := range lines {
		if strings.HasPrefix(line, "API_TOKEN=") {
			token := strings.TrimPrefix(line, "API_TOKEN=")
			viper.Set("defaults.api_token", token)
		}
	}
}

var timerCmd = &cobra.Command{
	Use:   "timer [on|off]",
	Short: "Управление таймером смены токена",
	Args:  cobra.MaximumNArgs(1),
	Run: func(cmd *cobra.Command, args []string) {
		if len(args) == 0 {
			status := "выключен"
			if viper.GetBool("defaults.token_timer_enabled") {
				status = "включен"
			}
			fmt.Printf("Таймер смены токена: %s\n", status)
			return
		}

		switch args[0] {
		case "on":
			viper.Set("defaults.token_timer_enabled", true)
			fmt.Println("Таймер смены токена включен")
			go startTokenTimer()
		case "off":
			viper.Set("defaults.token_timer_enabled", false)
			fmt.Println("Таймер смены токена выключен")
		default:
			fmt.Println("Используйте: timer on или timer off")
		}

		if err := viper.WriteConfig(); err != nil {
			fmt.Printf("❌ Ошибка сохранения настроек: %v\n", err)
		}
	},
}

var tokenTimer *time.Timer

func startTokenTimer() {
	if tokenTimer != nil {
		tokenTimer.Stop()
	}

	tokenTimer = time.AfterFunc(15*time.Minute, func() {
		fmt.Println("\n⚠️ ВНИМАНИЕ: Токен будет недействителен через 5 минут!")
		fmt.Println("Пожалуйста, обновите токен с помощью команды 'auth'")

		time.Sleep(10 * time.Minute)
		fmt.Println("\n Токен больше не действителен!")
		fmt.Println("Для продолжения работы обновите токен с помощью команды 'auth'")

		viper.Set("defaults.api_token", "")
	})
}

var statsCmd = &cobra.Command{
	Use:   "stats <file>",
	Short: "Показать статистику конфига",
	Run: func(cmd *cobra.Command, args []string) {
		content, err := core.ReadFile(args[0])
		if err != nil {
			fmt.Printf("Ошибка чтения файла: %v\n", err)
			return
		}

		cfg, err := core.ParseConfig(content)
		if err != nil {
			fmt.Printf("Ошибка парсинга: %v\n", err)
			return
		}

		fmt.Printf("Секций: %d\n", len(cfg))
		totalParams := 0
		for _, params := range cfg {
			totalParams += len(params)
		}
		fmt.Printf("Параметров: %d\n", totalParams)
	},
}

var validateCmd = &cobra.Command{
	Use:   "validate <file>",
	Short: "Проверить конфиг на ошибки",
	Run: func(cmd *cobra.Command, args []string) {
		content, _ := os.ReadFile(args[0])
		_, err := core.ParseConfig(string(content))
		if err != nil {
			fmt.Printf("Ошибка: %v\n", err)
			return
		}
		fmt.Println("Конфиг валиден")
	},
}

func resolveInputPath(inputPath, scriptDir, reportsDir string) string {
	if filepath.IsAbs(inputPath) {
		return inputPath
	}

	if core.FileExists(inputPath) {
		return inputPath
	}

	scriptPath := filepath.Join(scriptDir, inputPath)
	if core.FileExists(scriptPath) {
		return scriptPath
	}

	reportsPath := filepath.Join(reportsDir, inputPath)
	if core.FileExists(reportsPath) {
		return reportsPath
	}

	return inputPath
}

func initConfig() {
	home, err := os.UserHomeDir()
	if err != nil {
		fmt.Printf("❌ Ошибка определения домашней директории: %v\n", err)
		return
	}

	dirs := []string{
		filepath.Join(home, ".octochan"),
		filepath.Join(home, ".octochan", "scenarios"),
		filepath.Join(home, ".octochan", "reports"),
		filepath.Join(home, ".octochan", "snapshots"),
		filepath.Join(home, ".octochan", "logs"),
		filepath.Join(home, "octochan"),
	}

	for _, dir := range dirs {
		if err := os.MkdirAll(dir, 0755); err != nil {
			fmt.Printf("❌ Ошибка создания директории %s: %v\n", dir, err)
			return
		}
	}

	cfgPath := filepath.Join(home, "octochan", "config.yaml")
	viper.SetConfigFile(cfgPath)

	loadEnv()

	if _, err := os.Stat(cfgPath); os.IsNotExist(err) {
		viper.Set("defaults.api_url", "https://rlm.sigma.sbrf.ru/api/tasks.json")
		viper.Set("defaults.scenario_path", filepath.Join(home, ".octochan", "scenarios"))
		viper.Set("defaults.auto_check_status", false)
		viper.Set("defaults.max_parallel_tasks", 5)
		viper.Set("defaults.log_path", filepath.Join(home, ".octochan", "logs"))
		viper.Set("defaults.log_max_size", 10)
		viper.Set("defaults.log_max_backups", 5)
		viper.Set("defaults.token_timer_enabled", true)
		if err := viper.WriteConfig(); err != nil {
			fmt.Printf("❌ Ошибка создания конфига: %v\n", err)
		}
	}

	if err := viper.ReadInConfig(); err == nil {
		fmt.Println("⚙️ Используется конфиг:", viper.ConfigFileUsed())
	}

	if viper.GetBool("defaults.token_timer_enabled") && viper.GetString("defaults.api_token") != "" {
		go startTokenTimer()
	}
}
func showLogs(tail int) {
	logPath := viper.GetString("defaults.log_path")
	if logPath == "" {
		home, _ := os.UserHomeDir()
		logPath = filepath.Join(home, ".octochan", "logs")
	}

	logFile := filepath.Join(logPath, "octochan.log")

	if _, err := os.Stat(logFile); os.IsNotExist(err) {
		fmt.Println("ℹ️ Лог-файл ещё не создан, пока нет записей")
		return
	}

	content, err := os.ReadFile(logFile)
	if err != nil {
		fmt.Printf("❌ Ошибка чтения логов: %v\n", err)
		return
	}

	lines := strings.Split(string(content), "\n")

	if tail <= 0 || tail >= len(lines) {
		fmt.Println(string(content))
		return
	}

	start := len(lines) - tail
	if start < 0 {
		start = 0
	}

	fmt.Println("Последние", tail, "строк логов:")
	for _, line := range lines[start:] {
		fmt.Println(line)
	}
}

func initLogger() {
	logPath := viper.GetString("defaults.log_path")
	if logPath == "" {
		home, _ := os.UserHomeDir()
		logPath = filepath.Join(home, ".octochan", "logs")
	}

	if err := os.MkdirAll(logPath, 0755); err != nil {
		fmt.Printf("❌ Ошибка создания директории логов: %v\n", err)
		os.Exit(1)
	}

	logFile := filepath.Join(logPath, "rlm-cli.log")
	writer := &lumberjack.Logger{
		Filename:   logFile,
		MaxSize:    viper.GetInt("defaults.log_max_size"),
		MaxBackups: viper.GetInt("defaults.log_max_backups"),
		Compress:   true,
	}

	log.SetOutput(io.MultiWriter(os.Stdout, writer))
	log.SetFlags(log.LstdFlags | log.Lshortfile)
}

func watchModules() {
	fm, err := core.NewFileManager()
	if err != nil {
		log.Printf("❌ Не удалось инициализировать FileManager: %v", err)
		return
	}

	watcher, err := fsnotify.NewWatcher()
	if err != nil {
		log.Printf("❌ Не удалось создать watcher: %v", err)
		return
	}
	defer watcher.Close()

	err = watcher.Add(fm.ModulesDir())
	if err != nil {
		log.Printf("❌ Не удалось добавить директорию для наблюдения: %v", err)
		return
	}

	log.Println("Наблюдение за изменениями модулей запущено")

	for {
		select {
		case event, ok := <-watcher.Events:
			if !ok {
				return
			}

			if event.Op&fsnotify.Write == fsnotify.Write &&
				strings.HasSuffix(event.Name, ".hcplugin") {
				log.Printf("Обнаружено изменение модуля: %s", event.Name)
				if err := core.GetModuleManager().LoadHashicorpPlugin(event.Name); err != nil {
					log.Printf("⚠️ Не удалось перезагрузить модуль %s: %v", event.Name, err)
				} else {
					log.Printf("✅ Модуль %s успешно перезагружен", event.Name)
					RefreshCommands()
				}
			}

		case err, ok := <-watcher.Errors:
			if !ok {
				return
			}
			log.Printf("Ошибка watcher: %v", err)
		}
	}
}

var lastIfResult *bool
var ifCmd = &cobra.Command{
	Use:   "if [файл] [секция.параметр] [оператор] [значение] [результат]",
	Short: "Условный оператор для проверки значений в конфиге",
	Example: `if config.conf server.port == 8080 "Порт корректен"
if config.conf database.enabled != false "Включите базу данных"`,
	Args: cobra.ExactArgs(5),
	Run: func(cmd *cobra.Command, args []string) {
		filePath := args[0]
		paramPath := args[1]
		operator := args[2]
		expectedValue := args[3]
		resultMessage := args[4]

		content, err := os.ReadFile(filePath)
		if err != nil {
			fmt.Printf("❌ Ошибка чтения файла: %v\n", err)
			return
		}

		cfg, err := core.ParseConfig(string(content))
		if err != nil {
			fmt.Printf("❌ Ошибка парсинга конфига: %v\n", err)
			return
		}

		parts := strings.Split(paramPath, ".")
		if len(parts) != 2 {
			fmt.Printf("❌ Неверный формат параметра. Используйте: section.param\n")
			return
		}

		section, param := parts[0], parts[1]

		currentValue, exists := cfg[section][param]
		if !exists {
			fmt.Printf("❌ Параметр %s не найден в секции %s\n", param, section)
			return
		}

		isConditionMet := false

		switch operator {
		case "==":
			isConditionMet = (currentValue == expectedValue)
		case "!=":
			isConditionMet = (currentValue != expectedValue)
		case ">":

			currentNum, err1 := strconv.Atoi(currentValue)
			expectedNum, err2 := strconv.Atoi(expectedValue)
			if err1 == nil && err2 == nil {
				isConditionMet = (currentNum > expectedNum)
			} else {
				isConditionMet = (currentValue > expectedValue)
			}
		case "<":
			currentNum, err1 := strconv.Atoi(currentValue)
			expectedNum, err2 := strconv.Atoi(expectedValue)
			if err1 == nil && err2 == nil {
				isConditionMet = (currentNum < expectedNum)
			} else {
				isConditionMet = (currentValue < expectedValue)
			}
		case ">=":
			currentNum, err1 := strconv.Atoi(currentValue)
			expectedNum, err2 := strconv.Atoi(expectedValue)
			if err1 == nil && err2 == nil {
				isConditionMet = (currentNum >= expectedNum)
			} else {
				isConditionMet = (currentValue >= expectedValue)
			}
		case "<=":
			currentNum, err1 := strconv.Atoi(currentValue)
			expectedNum, err2 := strconv.Atoi(expectedValue)
			if err1 == nil && err2 == nil {
				isConditionMet = (currentNum <= expectedNum)
			} else {
				isConditionMet = (currentValue <= expectedValue)
			}
		case "contains":
			isConditionMet = strings.Contains(currentValue, expectedValue)
		case "startsWith":
			isConditionMet = strings.HasPrefix(currentValue, expectedValue)
		case "endsWith":
			isConditionMet = strings.HasSuffix(currentValue, expectedValue)
		default:
			fmt.Printf(" Неподдерживаемый оператор: %s\n", operator)
			fmt.Println("Доступные операторы: ==, !=, >, <, >=, <=, contains, startsWith, endsWith")
			return
		}

		lastIfResult = &isConditionMet
		if isConditionMet {
			fmt.Printf(" %s\n", resultMessage)
			fmt.Printf("   %s = %s %s %s\n", paramPath, currentValue, operator, expectedValue)
		} else {
			fmt.Printf(" Условие не выполнено: %s %s %s\n",
				currentValue, operator, expectedValue)
		}
	},
}
var applyCmd = &cobra.Command{
	Use:   "apply [-rlm] [file] [custom_params...]",
	Short: "Применить сценарий или конфигурацию",
	Args:  cobra.MinimumNArgs(0),
	Run: func(cmd *cobra.Command, args []string) {
		useRLM, _ := cmd.Flags().GetBool("rlm")

		if useRLM {
			log.Println("=== Starting new apply operation ===")
			defer log.Println("=== Apply operation completed ===")

			var scenarioData []byte
			var customParams map[string]string

			if len(args) > 0 && args[0] != "-" {
				data, err := os.ReadFile(args[0])
				if err != nil {
					fmt.Printf("❌ Ошибка чтения файла: %v\n", err)
					return
				}
				scenarioData = data
				if len(args) > 1 {
					customParams = make(map[string]string)
					for _, param := range args[1:] {
						parts := strings.SplitN(param, "=", 2)
						if len(parts) == 2 {
							customParams[parts[0]] = parts[1]
							log.Printf("Added custom param: %s=%s", parts[0], parts[1])
						} else {
							log.Printf("⚠️ Invalid parameter format: %s", param)
						}
					}
				}
			} else {
				stdinData, err := io.ReadAll(os.Stdin)
				if err != nil {
					fmt.Printf("❌ Ошибка чтения stdin: %v\n", err)
					return
				}
				scenarioData = stdinData

				if len(args) > 0 && args[0] == "-" {
					customParams = make(map[string]string)
					for _, param := range args[1:] {
						parts := strings.SplitN(param, "=", 2)
						if len(parts) == 2 {
							customParams[parts[0]] = parts[1]
							log.Printf("Added custom param: %s=%s", parts[0], parts[1])
						} else {
							log.Printf("⚠️ Invalid parameter format: %s", param)
						}
					}
				} else if len(args) > 0 {
					customParams = make(map[string]string)
					for _, param := range args {
						parts := strings.SplitN(param, "=", 2)
						if len(parts) == 2 {
							customParams[parts[0]] = parts[1]
							log.Printf("Added custom param: %s=%s", parts[0], parts[1])
						} else {
							log.Printf("⚠️ Invalid parameter format: %s", param)
						}
					}
				}
			}

			token := viper.GetString("defaults.api_token")
			if token == "" {
				fmt.Println("❌ Токен не установлен. Используйте команду 'auth' для установки токена")
				return
			}

			taskIDs, err := core.ExecuteScenarioData(scenarioData, customParams)
			if err != nil {
				fmt.Printf("❌ Ошибка выполнения сценария: %v\n", err)
				return
			}

			fmt.Println("✅ Созданные задачи:")
			for _, taskID := range taskIDs {
				fmt.Printf("- %s\n", taskID)
			}

			if viper.GetBool("defaults.auto_check_status") {
				fmt.Println("\n🔄 Проверка статусов задач...")
				for _, taskID := range taskIDs {
					status, err := core.GetTaskStatus(taskID)
					if err != nil {
						fmt.Printf("⚠️ Не удалось проверить статус задачи %s: %v\n", taskID, err)
					} else {
						fmt.Printf("- %s: %s\n", taskID, status["status"])
					}
				}
			}
		} else {
			fmt.Println("Применение обычного конфига...")

			if len(args) == 0 {
				fmt.Println("❌ Для обычного применения укажите файл конфигурации")
				return
			}

			var configData []byte
			var err error

			if args[0] == "-" {
				configData, err = io.ReadAll(os.Stdin)
				if err != nil {
					fmt.Printf("❌ Ошибка чтения stdin: %v\n", err)
					return
				}
			} else {
				configData, err = os.ReadFile(args[0])
				if err != nil {
					fmt.Printf("❌ Ошибка чтения файла: %v\n", err)
					return
				}
			}

			fmt.Printf("Применяем конфиг (%d bytes)...\n", len(configData))
		}
	},
}

func inspectModule(path string) error {
	if !strings.HasSuffix(path, ".hcplugin") {
		return fmt.Errorf("поддерживаются только .hcplugin модули")
	}

	if watcher != nil {
		if err := watcher.Remove(path); err != nil {
			log.Printf("⚠️ Не удалось отключить watcher: %v", err)
		}
		defer func() {
			if err := watcher.Add(path); err != nil {
				log.Printf("⚠️ Не удалось восстановить watcher: %v", err)
			}
		}()
	}

	if _, err := os.Stat(path); os.IsNotExist(err) {
		return fmt.Errorf("файл модуля не найден: %s", path)
	}

	logger := hclog.New(&hclog.LoggerOptions{
		Name:   "module-inspector",
		Output: os.Stdout,
		Level:  hclog.Info,
	})

	client := plugin.NewClient(&plugin.ClientConfig{
		HandshakeConfig: plugin.HandshakeConfig{
			ProtocolVersion:  1,
			MagicCookieKey:   "OCTOCHAN_PLUGIN",
			MagicCookieValue: "octochan-2025",
		},
		Plugins: map[string]plugin.Plugin{
			"command": &core.CommandPlugin{},
		},
		Cmd:              exec.Command(path),
		Logger:           logger,
		AllowedProtocols: []plugin.Protocol{plugin.ProtocolGRPC},
		StartTimeout:     5 * time.Second,
		Stderr:           os.Stderr,
	})

	defer func() {
		client.Kill()
		time.Sleep(100 * time.Millisecond)
	}()

	rpcClient, err := client.Client()
	if err != nil {
		return fmt.Errorf("RPC подключение: %w", err)
	}

	ctx, cancel := context.WithTimeout(context.Background(), 10*time.Second)
	defer cancel()

	raw, err := rpcClient.Dispense("command")
	if err != nil {
		return fmt.Errorf("не удалось получить интерфейс: %w", err)
	}
	if ctx.Err() == context.DeadlineExceeded {
		return fmt.Errorf("таймаут проверки модуля")
	}

	module, ok := raw.(core.CommandModule)
	if !ok {
		return fmt.Errorf("неверный тип модуля")
	}

	fmt.Printf("\n=== Информация о модуле ===\n")
	fmt.Printf("Файл: %s\n", path)
	fmt.Printf("Имя: %s\n", module.Name())
	fmt.Printf("Версия: %s\n", module.Version())

	cmds := module.GetCommands()
	if len(cmds) == 0 {
		fmt.Println("⚠️ Модуль не предоставляет команд")
		return nil
	}
	fmt.Println("Команды:")
	for _, cmd := range cmds {
		desc := cmd.Short
		if desc == "" {
			desc = "(нет описания)"
		}
		fmt.Printf("  %-10s - %s\n", cmd.Use, desc)

		if cmd.Example != "" {
			fmt.Printf("    Пример: %s\n", cmd.Example)
		}
		if cmd.Annotations != nil {
			fmt.Printf("    Аннотации: %v\n", cmd.Annotations)
		}
	}

	return nil
}

func loadModules() {
	mm := core.GetModuleManager()
	if len(mm.GetCommands()) > 0 {
		return
	}

	fm, err := core.NewFileManager()
	if err != nil {
		log.Printf("⚠️ Не удалось инициализировать FileManager: %v", err)
		return
	}

	if err := core.GetModuleManager().LoadModulesFromDir(fm.ModulesDir()); err != nil {
		log.Printf("⚠️ Ошибка при загрузке модулей: %v", err)
	}
	if watcher == nil {
		go watchModules()
	}
}

func loadModuleCommands() {
	existingCommands := make(map[string]bool)
	for _, c := range rootCmd.Commands() {
		existingCommands[c.Use] = true
	}

	for _, cmd := range core.GetModuleManager().GetCommands() {
		if !existingCommands[cmd.Use] {
			if cmd.Annotations == nil {
				cmd.Annotations = make(map[string]string)
			}
			cmd.Annotations["source"] = "module"

			rootCmd.AddCommand(cmd)
			log.Printf("Added module command: %s", cmd.Use)
		}
	}
}

func RefreshCommands() {
	var newCommands []*cobra.Command
	for _, cmd := range rootCmd.Commands() {
		if !isModuleCommand(cmd) {
			newCommands = append(newCommands, cmd)
		}
	}
	rootCmd.ResetCommands()
	rootCmd.AddCommand(newCommands...)
	loadModuleCommands()
}

func isModuleCommand(cmd *cobra.Command) bool {
	if cmd.Annotations != nil && cmd.Annotations["source"] == "module" {
		return true
	}
	return false
}

var printCmd = &cobra.Command{
	Use:   "print [file]",
	Short: "Print file or stdin content",
	Args:  cobra.MaximumNArgs(1),
	Run: func(cmd *cobra.Command, args []string) {
		if len(args) > 0 {
			content, err := os.ReadFile(args[0])
			if err != nil {
				fmt.Printf("❌ Error reading file: %v\n", err)
				return
			}
			fmt.Print(string(content))
		} else {
			stat, _ := os.Stdin.Stat()
			if (stat.Mode() & os.ModeCharDevice) == 0 {
				content, _ := io.ReadAll(os.Stdin)
				fmt.Print(string(content))
			} else {
				cmd.Help()
				fmt.Println("\n❌ Укажите файл или используйте pipe:")
				fmt.Println("  print file.txt")
				fmt.Println("  echo 'hello' | print")
			}
		}
	},
}
var elseCmd = &cobra.Command{
	Use:   "else [файл] [секция.параметр] [оператор] [значение] [результат]",
	Short: "Альтернативное условие (выполняется если предыдущий if не сработал)",
	Example: `if config.conf server.port == 8080 "Порт корректен"
else config.conf server.port != 8080 "Исправьте порт на 8080"`,
	Args: cobra.ExactArgs(5),
	Run: func(cmd *cobra.Command, args []string) {

		if lastIfResult == nil {
			fmt.Println("❌ Команда else должна использоваться после команды if")
			return
		}
		if *lastIfResult {
			fmt.Println("ℹ️ Предыдущее условие if выполнено, else пропускается")
			return
		}

		filePath := args[0]
		paramPath := args[1]
		operator := args[2]
		expectedValue := args[3]
		resultMessage := args[4]

		content, err := os.ReadFile(filePath)
		if err != nil {
			fmt.Printf("❌ Ошибка чтения файла: %v\n", err)
			return
		}

		cfg, err := core.ParseConfig(string(content))
		if err != nil {
			fmt.Printf("❌ Ошибка парсинга конфига: %v\n", err)
			return
		}

		parts := strings.Split(paramPath, ".")
		if len(parts) != 2 {
			fmt.Printf("❌ Неверный формат параметра. Используйте: section.param\n")
			return
		}

		section, param := parts[0], parts[1]

		currentValue, exists := cfg[section][param]
		if !exists {
			fmt.Printf("❌ Параметр %s не найден в секции %s\n", param, section)
			return
		}

		isConditionMet := false

		switch operator {
		case "==":
			isConditionMet = (currentValue == expectedValue)
		case "!=":
			isConditionMet = (currentValue != expectedValue)
		case ">":
			currentNum, err1 := strconv.Atoi(currentValue)
			expectedNum, err2 := strconv.Atoi(expectedValue)
			if err1 == nil && err2 == nil {
				isConditionMet = (currentNum > expectedNum)
			} else {
				isConditionMet = (currentValue > expectedValue)
			}
		case "<":
			currentNum, err1 := strconv.Atoi(currentValue)
			expectedNum, err2 := strconv.Atoi(expectedValue)
			if err1 == nil && err2 == nil {
				isConditionMet = (currentNum < expectedNum)
			} else {
				isConditionMet = (currentValue < expectedValue)
			}
		case ">=":
			currentNum, err1 := strconv.Atoi(currentValue)
			expectedNum, err2 := strconv.Atoi(expectedValue)
			if err1 == nil && err2 == nil {
				isConditionMet = (currentNum >= expectedNum)
			} else {
				isConditionMet = (currentValue >= expectedValue)
			}
		case "<=":
			currentNum, err1 := strconv.Atoi(currentValue)
			expectedNum, err2 := strconv.Atoi(expectedValue)
			if err1 == nil && err2 == nil {
				isConditionMet = (currentNum <= expectedNum)
			} else {
				isConditionMet = (currentValue <= expectedValue)
			}
		case "contains":
			isConditionMet = strings.Contains(currentValue, expectedValue)
		case "startsWith":
			isConditionMet = strings.HasPrefix(currentValue, expectedValue)
		case "endsWith":
			isConditionMet = strings.HasSuffix(currentValue, expectedValue)
		default:
			fmt.Printf("❌ Неподдерживаемый оператор: %s\n", operator)
			return
		}

		if isConditionMet {
			fmt.Printf("✅ %s\n", resultMessage)
			fmt.Printf("   %s = %s %s %s\n", paramPath, currentValue, operator, expectedValue)
		} else {
			fmt.Printf("❌ Условие else не выполнено: %s %s %s\n",
				currentValue, operator, expectedValue)
		}
	},
}

var teeCmd = &cobra.Command{
	Use:   "tee [file]",
	Short: "Read stdin and write to stdout and file",
	Args:  cobra.MaximumNArgs(1),
	Run: func(cmd *cobra.Command, args []string) {
		content, _ := io.ReadAll(os.Stdin)
		fmt.Print(string(content))
		if len(args) > 0 {
			if err := os.WriteFile(args[0], content, 0644); err != nil {
				fmt.Printf("❌ Error writing to file: %v\n", err)
			}
		}
	},
}

func init() {
	rootCmd.SilenceErrors = true
	rootCmd.SilenceUsage = true
	cobra.OnInitialize(initConfig, initLogger, loadModules)
	diffCmd.Flags().BoolVarP(&fastMode, "fast", "f", false, "Только вывод в консоль без генерации файлов")
	rootCmd.AddCommand(PipeWrapper(diffCmd))
	rootCmd.AddCommand(PipeWrapper(validateCmd))
	rootCmd.AddCommand(PipeWrapper(findCmd))
	rootCmd.AddCommand(PipeWrapper(patchCmd))
	rootCmd.AddCommand(PipeWrapper(statsCmd))
	rootCmd.SetHelpCommand(helpCmd)
	rootCmd.AddCommand(helpCmd)
	rootCmd.AddCommand(PipeWrapper(printCmd))
	rootCmd.AddCommand(PipeWrapper(teeCmd))
	rootCmd.PersistentFlags().StringVar(&cfgFile, "config", "", "Конфиг (default: ~/.rlm-cli/config.yaml)")
	rootCmd.AddCommand(PipeWrapper(saveScenarioCmd))
	rootCmd.AddCommand(PipeWrapper(ifCmd))
	rootCmd.AddCommand(authCmd)
	rootCmd.AddCommand(statusCmd)
	applyCmd.Flags().BoolP("rlm", "r", false, "Использовать RLM сценарий")
	rootCmd.AddCommand(PipeWrapper(applyCmd))
	logsCmd.Flags().Int("tail", 0, "Показать последние N строк логов (0 - все логи)")
	rootCmd.AddCommand(logsCmd)
	rootCmd.AddCommand(listModulesCmd)
	rootCmd.AddCommand(installCmd)
	rootCmd.AddCommand(timerCmd)
	rootCmd.AddCommand(inspectCmd)

	loadModuleCommands()
}
